# Generated by Django 5.1.6 on 2025-04-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_created_at_audiofile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AudioMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('bit_rate', models.IntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, max_length=50, null=True)),
                ('channels', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_metadata', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
